disabled_rules:
  - multiple_closures_with_trailing_closure
  - force_cast
excluded: 
  - Pods
  - submodules
file_length:
  warning: 500
  error: 1200
line_length: 200
large_tuple: 
  - 10
force_cast: warning
force_try: warning
function_body_length: 
  300
cyclomatic_complexity: 
  - 100
type_body_length:
  - 3000 # warning
  - 4000 # error
identifier_name:
  min_length: 1
  validates_start_with_lowercase: false
file_length: 
  - 1500
type_name:
  max_length: # warning and error
    warning: 70
    error: 70
